### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by renews** [renews/dot-files#14]
- [ ] from MAS to cask, was work only sometimes.
- [ ] auto git clone a bunch of projects to specified folders
- [ ] sudo chown /usr/local
- [ ] git prompt can't use wget yet
- [ ] Setup git missing validation 
- [ ] Need sudo to export bash to /etc/shells
- [ ] execute brew linkapps emacs-plus after its's installation
- [ ] elastic search plugin error
- [ ] All gems from Ruby installation seems to be using native ruby instead of rbenv one's.
- [ ] Elixir is not installing
- [ ] Readme bug when installing heroku
- [ ] Duplicated install for virtual box, visual-studio-code
- [ ] Ignoring input on the installation of visual-studio-code
